variables:
  WORK: "/tmp"
  LMOD_REDIRECT: "yes"
  MODULES_DIR: "/util/opt/modulefiles"

stages:
  - test
  - deploy

test-modules:
  stage: test
  image: unlhcc/rhino-build-el7
  except:
    - master
  tags:
    - docker
  before_script:
    - ln -s $CI_PROJECT_DIR $MODULES_DIR
    - source /util/opt/lmod/lmod/init/profile
  script:
    - module av > /dev/null
    - module spider > /dev/null

test-paths:
  stage: test
  image: unlhcc/rhino-build-el7
  except:
    - master
  tags:
    - rhino
  script:
    - scripts/test_changed_modules.sh

deploy:
  stage: deploy
  environment:
    name: rhino_production
    url: https://rhino.unl.edu
  resource_group: production
  image: unlhcc/rhino-build-el7
  only:
    - master
  tags:
    - rhino
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  script:
    - cd $MODULES_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA
